# Generated by Django 5.1.5 on 2025-01-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureauetude',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='startup',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
