# Generated by Django 5.1.5 on 2025-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bureauetude_password_startup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='genre',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50),
        ),
    ]
