# Generated by Django 5.1.5 on 2025-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_startup_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
