# Generated by Django 5.1.5 on 2025-02-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_personne_is_active_startup_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personne',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='startup',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='personne',
            table='personne',
        ),
        migrations.AlterModelTable(
            name='startup',
            table='startup',
        ),
    ]
