# Generated by Django 5.1.5 on 2025-03-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_personne_est_actif_remove_startup_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='date_naissance_leader',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='startup',
            name='genre_leader',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50),
        ),
        migrations.AlterField(
            model_name='startup',
            name='nom_leader',
            field=models.CharField(max_length=255),
        ),
    ]
