# Generated by Django 5.1.5 on 2025-03-06 23:53

import account.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_startup_date_naissance_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='id_startup',
        ),
        migrations.CreateModel(
            name='BureauEtudeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bureau_logos')),
                ('site_web', models.URLField(blank=True, null=True)),
                ('domaines_expertise', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.bureauetude')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='account.bureauetude')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='account.startup')),
            ],
            options={
                'unique_together': {('bureau', 'startup')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('bureau', "Bureau d'Étude"), ('startup', 'Startup')], max_length=10)),
                ('sender_id', models.IntegerField()),
                ('receiver_type', models.CharField(choices=[('bureau', "Bureau d'Étude"), ('startup', 'Startup')], max_length=10)),
                ('receiver_id', models.IntegerField()),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Audio')], default='text', max_length=5)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=account.models.message_file_path)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.chat')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=account.models.message_file_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='account.message')),
            ],
        ),
        migrations.CreateModel(
            name='PersonneProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.personne')),
            ],
        ),
        migrations.CreateModel(
            name='StartupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.personne')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.startup')),
            ],
            options={
                'unique_together': {('startup', 'personne')},
            },
        ),
        migrations.AddField(
            model_name='startup',
            name='members',
            field=models.ManyToManyField(related_name='member_of_startups', through='account.StartupMember', to='account.personne'),
        ),
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='startup_logos')),
                ('site_web', models.URLField(blank=True, null=True)),
                ('social_media', models.JSONField(blank=True, null=True)),
                ('stade_developpement', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.startup')),
            ],
        ),
    ]
