# Generated by Django 5.1.5 on 2025-04-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_personne_id_startup_bureauetudeprofile_chat_and_more'),
    ]

    operations = [
    ]
