# Generated by Django 5.1.5 on 2025-04-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20250418_2028'),
    ]

    operations = [
    ]
