# Generated by Django 5.1.5 on 2025-04-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20250419_1859'),
    ]

    operations = [
    ]
